apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":443,"protocol":"HTTPS","serviceName":"addysnip-dev:api","ingressName":"addysnip-dev:api","hostname":"api.dev.addysnip.com","path":"/","allNodes":false}]'
  name: api
  namespace: addysnip
spec:
  rules:
  - host: api.dev.addysnip.com
    http:
      paths:
      - backend:
          service:
            name: api
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.dev.addysnip.com
    secretName: addysnip-com-tls
