apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: addysnip
spec:
  ingressClassName: nginx
  rules:
  - host: api.addysnip.com
    http:
      paths:
      - backend:
          service:
            name: api
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.addysnip.com
    secretName: addysnip-com-tls
