apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: addysnip
spec:
  clusterIP: 10.245.11.198
  clusterIPs:
  - 10.245.11.198
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 3000tcp
    port: 3000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-api
