apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-service
  namespace: addysnip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-domain-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-12T01:18:26Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-domain-service
    spec:
      containers:
      - env:
        - name: K8S_NAMESPACE
          value: redirector-dev
        - name: DEBUG
          value: "true"
        - name: EXT_SVC_HOSTNAME
          value: "svc.addysnip.com"
        envFrom:
        - secretRef:
            name: database
            optional: false
        - secretRef:
            name: rabbitmq
            optional: false
        image: gcr.io/addysnip/domain-service:2351c217
        imagePullPolicy: Always
        name: domain-service
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gar-json-key
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: redirector-service
      serviceAccountName: redirector-service
      terminationGracePeriodSeconds: 30
