apiVersion: v1
kind: ServiceAccount
metadata:
  name: redirector-service
  namespace: addysnip
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  redirector-service
  namespace: redirector
rules:
- apiGroups: 
    - "cert-manager.io"
  resources: 
    - certificates
    - certificates/status
    - certificaterequests
    - certificaterequests/status
  verbs: 
    - create
    - delete
    - update
    - get
    - list
    - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redirector-service
  namespace: redirector
subjects:
- kind: ServiceAccount
  name: redirector-service
  namespace: addysnip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redirector-service
