apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-service
  namespace: addysnip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-tasks-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-13T06:03:27Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-tasks-service
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: database
            optional: false
        image: gcr.io/addysnip/tasks-service:93f3d7d7
        imagePullPolicy: Always
        name: tasks-service
        ports:
        - containerPort: 5000
          name: 5000tcp
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gar-json-key
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
