apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-addysnip

resources:
- namespaces/redirector.yaml
- certificate/certificate.yaml
- secrets/extsecret-analytics-service.yaml
- secrets/extsecret-api.yaml
- secrets/extsecret-billing.yaml
- secrets/extsecret-database.yaml
- secrets/extsecret-gar-image-pull.yaml
- secrets/extsecret-path-service.yaml
- secrets/extsecret-rabbitmq.yaml
- secrets/extsecret-redis.yaml
- secrets/extsecret-smtp-noreply.yaml
- secrets/extsecret-stripe-webhook.yaml
- secrets/extsecret-discord-webhook.yaml
- secrets/extsecret-tasks-service.yaml
- analytics-service/deployment-analytics-service.yaml
- analytics-service/service-analytics-service.yaml
- analytics-service/cronjob-analytics.yaml
- api/deployment-api.yaml
- api/ingress-api.yaml
- api/service-api.yaml
- billing/deployment-billing.yaml
- billing/service-billing.yaml
- dashboard-reloader/deployment.yaml
- dashboard-reloader/rbac.yaml
- delayed-service/deployment-delayed-service.yaml
- domain-service/deployment-domain-service.yaml
- domain-service/rbac.yaml
- emailer/deployment-emailer.yaml
- emailer/service-emailer.yaml
- path-service/deployment-path-service.yaml
- path-service/service-path-service.yaml
- redirector-service/deployment-redirector.yaml
- redirector-service/service-redirector.yaml
- tasks-service/deployment-tasks-service.yaml
- ui/deployment-ui.yaml
- ui/ingress-ui.yaml
- ui/service-ui.yaml
- ui-dashboard/deployment-ui-dashboard.yaml
- ui-dashboard/ingress-ui-dashboard.yaml
- ui-dashboard/service-ui-dashboard.yaml
- ui-docs/deployment.yaml
- ui-docs/ingress.yaml
- ui-docs/service.yaml
- clusterissuer.yaml
images:
- name: gcr.io/addysnip/analytics-service
  newName: gcr.io/addysnip/analytics-service
  newTag: d98582e4
- name: gcr.io/addysnip/api
  newName: gcr.io/addysnip/api
  newTag: dd1e794b
- name: gcr.io/addysnip/billing
  newName: gcr.io/addysnip/billing
  newTag: 590bdf77
- name: gcr.io/addysnip/delayed-service
  newName: gcr.io/addysnip/delayed-service
  newTag: cea7bb73
- name: gcr.io/addysnip/docs
  newName: gcr.io/addysnip/docs
  newTag: dc39ab7c
- name: gcr.io/addysnip/domain-service
  newName: gcr.io/addysnip/domain-service
  newTag: e9838e80
- name: gcr.io/addysnip/emailer
  newName: gcr.io/addysnip/emailer
  newTag: 0a81fed0
- name: gcr.io/addysnip/path-service
  newName: gcr.io/addysnip/path-service
  newTag: c0689f90
- name: gcr.io/addysnip/redirector-service
  newName: gcr.io/addysnip/redirector-service
  newTag: b0e370e9
- name: gcr.io/addysnip/tasks-service
  newName: gcr.io/addysnip/tasks-service
  newTag: a2fd75f9
- name: gcr.io/addysnip/ui
  newName: gcr.io/addysnip/ui
  newTag: a72e0547
- name: gcr.io/addysnip/ui-dashboard
  newName: gcr.io/addysnip/ui-dashboard
  newTag: adb85259
