apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-addysnip

resources:
- namespaces/redirector.yaml
- certificate/certificate.yaml
- secrets/extsecret-analytics-service.yaml
- secrets/extsecret-api.yaml
- secrets/extsecret-billing.yaml
- secrets/extsecret-database.yaml
- secrets/extsecret-gar-image-pull.yaml
- secrets/extsecret-path-service.yaml
- secrets/extsecret-rabbitmq.yaml
- secrets/extsecret-redis.yaml
- secrets/extsecret-smtp-noreply.yaml
- secrets/extsecret-stripe-webhook.yaml
- secrets/extsecret-discord-webhook.yaml
- analytics-service/deployment-analytics-service.yaml
- analytics-service/service-analytics-service.yaml
- analytics-service/cronjob-analytics.yaml
- api/deployment-api.yaml
- api/ingress-api.yaml
- api/service-api.yaml
- billing/deployment-billing.yaml
- billing/service-billing.yaml
- delayed-service/deployment-delayed-service.yaml
- domain-service/deployment-domain-service.yaml
- domain-service/rbac.yaml
- emailer/deployment-emailer.yaml
- emailer/service-emailer.yaml
- path-service/deployment-path-service.yaml
- path-service/service-path-service.yaml
- redirector-service/deployment-redirector.yaml
- redirector-service/service-redirector.yaml
- tasks-service/deployment-tasks-service.yaml
- ui/deployment-ui.yaml
- ui/ingress-ui.yaml
- ui/service-ui.yaml
- ui-dashboard/deployment-ui-dashboard.yaml
- ui-dashboard/ingress-ui-dashboard.yaml
- ui-dashboard/service-ui-dashboard.yaml
- clusterissuer.yaml
images:
- name: gcr.io/addysnip/api
  newName: gcr.io/addysnip/api
  newTag: 281b6d5b
