apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-addysnip-dev-emailer
  name: emailer
  namespace: addysnip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-addysnip-dev-emailer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-06T04:09:52Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-addysnip-dev-emailer
    spec:
      containers:
      - env:
        - name: RABBITMQ_QUEUE
          value: emailer
        envFrom:
        - secretRef:
            name: database
        - secretRef:
            name: rabbitmq
        - secretRef:
            name: smtp-noreply
        - secretRef:
            name: discord-error-webhook
            optional: false
        image: gcr.io/addysnip/emailer:956f19f1
        imagePullPolicy: Always
        name: emailer
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gar-json-key
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
