apiVersion: v1
kind: Service
metadata:
  name: emailer
  namespace: addysnip
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: default
    port: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-addysnip-dev-emailer
