apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-analytics
  namespace: addysnip
spec:
  schedule: "0 5 1,15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync-analytics
            image: gcr.io/addysnip/analytics-service:latest
            imagePullPolicy: Always
            command:
            - /app/app
            - -v
            - sync
            env:
            - name: RABBITMQ_QUEUE
              value: analytics
            envFrom:
            - secretRef:
                name: analytics-service
                optional: false
            - secretRef:
                name: rabbitmq
                optional: false
            - secretRef:
                name: database
                optional: false
            - secretRef:
                name: redis
                optional: false
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: gar-json-key