apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: addysnip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-analytics-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-13T22:51:44Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-analytics-service
    spec:
      containers:
      - command:
        - /app/app
        - -v
        - consumer
        env:
        - name: RABBITMQ_QUEUE
          value: analytics-dev
        envFrom:
        - secretRef:
            name: analytics-service
            optional: false
        - secretRef:
            name: rabbitmq
            optional: false
        - secretRef:
            name: database
            optional: false
        - secretRef:
            name: redis
            optional: false
        image: gcr.io/addysnip/analytics-service:2caa2880
        imagePullPolicy: Always
        name: analytics-service
        ports:
        - containerPort: 5000
          name: 5000tcp
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gar-json-key
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
