apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: addysnip-com
  namespace: addysnip
spec:
  issuerRef:
    name: addysnip-com-ca
    kind: ClusterIssuer
  dnsNames:
  - addysnip.com
  - "dev.addysnip.com"
  - "*.dev.addysnip.com"