apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: addysnip
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: SESSION_COOKIE
          value: "session-dev"