apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: extsecret-discord-error-webhook
  namespace: addysnip
spec:
  dataFrom:
  - key: dev-discord-error-webhook
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: extsecret-discord-error-webhook
  namespace: redirector
spec:
  dataFrom:
  - key: dev-discord-error-webhook