apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret-discord-error-webhook
  namespace: addysnip
spec:
  dataFrom:
  - extract:
      key: dev-discord-error-webhook
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret-discord-error-webhook
  namespace: redirector
spec:
  dataFrom:
  - extract:
      key: dev-discord-error-webhook