apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: gcr.io/addysnip/analytics-service
  newName: gcr.io/addysnip/analytics-service
  newTag: 59fd5bed
- name: gcr.io/addysnip/api
  newName: gcr.io/addysnip/api
  newTag: 429920c5
- name: gcr.io/addysnip/billing
  newName: gcr.io/addysnip/billing
  newTag: 1839d225
- name: gcr.io/addysnip/delayed-service
  newName: gcr.io/addysnip/delayed-service
  newTag: cea7bb73
- name: gcr.io/addysnip/domain-service
  newName: gcr.io/addysnip/domain-service
  newTag: 6636562d
- name: gcr.io/addysnip/emailer
  newName: gcr.io/addysnip/emailer
  newTag: 91d1da05
- name: gcr.io/addysnip/path-service
  newName: gcr.io/addysnip/path-service
  newTag: eee805c6
- name: gcr.io/addysnip/redirector
  newName: gcr.io/addysnip/redirector
  newTag: ae1b6dc5
- name: gcr.io/addysnip/redirector-service
  newName: gcr.io/addysnip/redirector-service
  newTag: adab5310
- name: gcr.io/addysnip/tasks-service
  newName: gcr.io/addysnip/tasks-service
  newTag: 0a8bfa52
- name: gcr.io/addysnip/ui
  newName: gcr.io/addysnip/ui
  newTag: 35c47ff2
- name: gcr.io/addysnip/ui-dashboard
  newName: gcr.io/addysnip/ui-dashboard
  newTag: 9ff0776d
patchesStrategicMerge:
- certificate.yaml
- ingress-api.yaml
- ingress-ui.yaml
- ingress-ui-dashboard.yaml
- extsecret-analytics-service.yaml
- extsecret-api.yaml
- extsecret-billing.yaml
- extsecret-database.yaml
- extsecret-path-service.yaml
- extsecret-rabbitmq.yaml
- extsecret-redis.yaml
- extsecret-stripe-webhook.yaml
- extsecret-discord-webhook.yaml
- deployment-api.yaml
- deployment-domain-service.yaml
