apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: gcr.io/addysnip/analytics-service
  newName: gcr.io/addysnip/analytics-service
  newTag: 6b3cc999
- name: gcr.io/addysnip/api
  newName: gcr.io/addysnip/api
  newTag: 5de68889
- name: gcr.io/addysnip/billing
  newName: gcr.io/addysnip/billing
  newTag: 103efa57
- name: gcr.io/addysnip/delayed-service
  newName: gcr.io/addysnip/delayed-service
  newTag: 756d495f
- name: gcr.io/addysnip/domain-service
  newName: gcr.io/addysnip/domain-service
  newTag: db0ebc26
- name: gcr.io/addysnip/emailer
  newName: gcr.io/addysnip/emailer
  newTag: 94c705a5
- name: gcr.io/addysnip/path-service
  newName: gcr.io/addysnip/path-service
  newTag: 453c6c6b
- name: gcr.io/addysnip/redirector
  newName: gcr.io/addysnip/redirector
  newTag: ae1b6dc5
- name: gcr.io/addysnip/redirector-service
  newName: gcr.io/addysnip/redirector-service
  newTag: fc7616b8
- name: gcr.io/addysnip/tasks-service
  newName: gcr.io/addysnip/tasks-service
  newTag: 978b46a2
- name: gcr.io/addysnip/ui
  newName: gcr.io/addysnip/ui
  newTag: f27cbd69
- name: gcr.io/addysnip/ui-dashboard
  newName: gcr.io/addysnip/ui-dashboard
  newTag: f30ab36f
patchesStrategicMerge:
- certificate.yaml
- ingress-api.yaml
- ingress-ui.yaml
- ingress-ui-dashboard.yaml
- extsecret-analytics-service.yaml
- extsecret-api.yaml
- extsecret-billing.yaml
- extsecret-database.yaml
- extsecret-path-service.yaml
- extsecret-rabbitmq.yaml
- extsecret-redis.yaml
- deployment-domain-service.yaml
