patchesStrategicMerge:
- certificate.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: gcr.addysnip/addysnip/emailer
  newName: gcr.addysnip/addysnip/emailer
  newTag: 2d5b0c71
- name: gcr.addysnip/addysnip/ui
  newName: gcr.addysnip/addysnip/ui
  newTag: cfbd9802
- name: gcr.addysnip/billing
  newName: gcr.addysnip/billing
  newTag: b0ebe125
- name: gcr.addysnip/delayed-service
  newName: gcr.addysnip/delayed-service
  newTag: 2f448df7
