apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: gcr.io/addysnip/analytics-service
  newName: gcr.io/addysnip/analytics-service
  newTag: e52b0fb3
- name: gcr.io/addysnip/api
  newName: gcr.io/addysnip/api
  newTag: 79eff3a5
- name: gcr.io/addysnip/billing
  newName: gcr.io/addysnip/billing
  newTag: 103efa57
- name: gcr.io/addysnip/delayed-service
  newName: gcr.io/addysnip/delayed-service
  newTag: c79527f0
- name: gcr.io/addysnip/domain-service
  newName: gcr.io/addysnip/domain-service
  newTag: 6b7d68e2
- name: gcr.io/addysnip/emailer
  newName: gcr.io/addysnip/emailer
  newTag: 94c705a5
- name: gcr.io/addysnip/path-service
  newName: gcr.io/addysnip/path-service
  newTag: ae369000
- name: gcr.io/addysnip/ui
  newName: gcr.io/addysnip/ui
  newTag: f27cbd69
- name: gcr.io/addysnip/ui-dashboard
  newName: gcr.io/addysnip/ui-dashboard
  newTag: c96055f8
patchesStrategicMerge:
- certificate.yaml
- ingress-api.yaml
- ingress-ui.yaml
- ingress-ui-dashboard.yaml
- extsecret-analytics-service.yaml
- extsecret-api.yaml
- extsecret-billing.yaml
- extsecret-database.yaml
- extsecret-path-service.yaml
- extsecret-rabbitmq.yaml
- extsecret-redis.yaml
- deployment-domain-service.yaml
