patchesStrategicMerge:
- certificate.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: gcr.addysnip/billing
  newName: gcr.addysnip/billing
  newTag: b0ebe125
