apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: gcr.io/addysnip/analytics-service
  newName: gcr.io/addysnip/analytics-service
  newTag: e52b0fb3
- name: gcr.io/addysnip/api
  newName: gcr.io/addysnip/api
  newTag: 74e608cb
- name: gcr.io/addysnip/billing
  newName: gcr.io/addysnip/billing
  newTag: 103efa57
- name: gcr.io/addysnip/delayed-service
  newName: gcr.io/addysnip/delayed-service
  newTag: c79527f0
- name: gcr.io/addysnip/domain-service
  newName: gcr.io/addysnip/domain-service
  newTag: 01c2f1f9
- name: gcr.io/addysnip/emailer
  newName: gcr.io/addysnip/emailer
  newTag: 056f070e
- name: gcr.io/addysnip/path-service
  newName: gcr.io/addysnip/path-service
  newTag: ae369000
- name: gcr.io/addysnip/ui
  newName: gcr.io/addysnip/ui
  newTag: ba975b79
- name: gcr.io/addysnip/ui-dashboard
  newName: gcr.io/addysnip/ui-dashboard
  newTag: 51aea460
patchesStrategicMerge:
- certificate.yaml
- ingress-api.yaml
- ingress-ui.yaml
- ingress-ui-dashboard.yaml
