apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret-smtp-noreply
  namespace: addysnip
spec:

  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: smtp-noreply
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: smtp-noreply
