apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret-discord-error-webhook
  namespace: addysnip
spec:

  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: discord-error-webhook
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: discord-error-webhook
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret-discord-error-webhook
  namespace: redirector
spec:

  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: discord-error-webhook
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: discord-error-webhook
