apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret-api
  namespace: addysnip
spec:

  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: api
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: api
