apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsecret-stripe-webhook
  namespace: addysnip
spec:

  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: stripe-webhook
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: stripe-webhook
