apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: extsecret-gar-image-pull
  namespace: addysnip
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: gar-json-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .garjson | toString }}"
  data:
  - secretKey: garjson
    remoteRef:
      key: gar-image-pull
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: extsecret-gar-image-pull
  namespace: redirector
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: gar-json-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .garjson | toString }}"
  data:
  - secretKey: garjson
    remoteRef:
      key: gar-image-pull