apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: extsecret-discord-error-webhook
  namespace: addysnip
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretstore
  target:
    name: discord-error-webhook
    creationPolicy: Owner
  dataFrom:
  - key: discord-error-webhook
