apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
  name: path-service
  namespace: addysnip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-path-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-13T06:03:27Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-path-service
    spec:
      containers:
      - env:
        - name: RABBITMQ_QUEUE
          value: path-dev
        envFrom:
        - secretRef:
            name: database
            optional: false
        - secretRef:
            name: rabbitmq
            optional: false
        - secretRef:
            name: path-service
            optional: false
        - secretRef:
            name: redis
            optional: false
        image: gcr.io/addysnip/path-service:bc36b8cb
        imagePullPolicy: Always
        name: path-service
        ports:
        - containerPort: 5000
          name: 5000tcp
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gar-json-key
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
