apiVersion: v1
kind: Service
metadata:
  name: path-service
  namespace: addysnip
spec:
  clusterIP: 10.245.150.229
  clusterIPs:
  - 10.245.150.229
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5000tcp
    port: 5000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-path-service
