apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  namespace: addysnip
spec:
  rules:
  - host: www.dev.addysnip.com
    http:
      paths:
      - backend:
          service:
            name: ui
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - www.dev.addysnip.com
    secretName: addysnip-com-tls
