apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":443,"protocol":"HTTPS","serviceName":"addysnip-dev:ui","ingressName":"addysnip-dev:ui","hostname":"www.dev.addysnip.com","path":"/","allNodes":false}]'
  name: ui
  namespace: addysnip
spec:
  rules:
  - host: www.dev.addysnip.com
    http:
      paths:
      - backend:
          service:
            name: ui
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - www.dev.addysnip.com
    secretName: addysnip-com-tls
