apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "19"
    field.cattle.io/publicEndpoints: '[{"addresses":["138.197.153.183"],"port":30000,"protocol":"TCP","serviceName":"addysnip-dev:billing-np","allNodes":true}]'
  name: billing
  namespace: addysnip
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-billing
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-01T03:52:20Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-addysnip-dev-billing
    spec:
      containers:
      - command:
        - /app/app
        - -v
        - consumer
        env:
        - name: RABBITMQ_QUEUE
          value: billing
        envFrom:
        - secretRef:
            name: billing
            optional: false
        - secretRef:
            name: database
            optional: false
        - secretRef:
            name: rabbitmq
            optional: false
        image: gcr.io/addysnip/billing:243a9ef7
        imagePullPolicy: Always
        name: billing
        ports:
        - containerPort: 5000
          name: 5000tcp
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gar-json-key
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
